DROP TABLE IF EXISTS attendee;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS imagepost;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS videopost;