DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS attendee;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS textPost;
DROP TABLE IF EXISTS imagePost;
DROP TABLE IF EXISTS videoPost;
<<<<<<< HEAD
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS users;
=======
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS attendee;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS textPost;
DROP TABLE IF EXISTS imagePost;
DROP TABLE IF EXISTS videoPost;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS attendee;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS textPost;
DROP TABLE IF EXISTS imagePost;
DROP TABLE IF EXISTS videoPost;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS attendee;
DROP TABLE IF EXISTS subscription;
>>>>>>> b61565309df8bde4ec991d10bf0ffdefa696383a
